name:                SimpleTypeChecker
version:             0.1.0.0
github:              "githubuser/SimpleTypeChecker"
license:             MIT
author:              "SmnTin"
maintainer:          "smn.pankv@gmail.com"
copyright:           "2022 Semyon Panenkov"

extra-source-files:
- LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A type checker for simply typed lambda calculus

dependencies:
- base >= 4.7 && < 5
- mtl  >=2    && <3

library:
  source-dirs: src

executables:
  SimpleTypeChecker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleTypeChecker

tests:
  SimpleTypeChecker-test:
    main:                TestSuite.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleTypeChecker
    - tasty >= 1.4
    - tasty-hunit >= 0.10
